version: "3.7"
services:
  # Start Mosquitto MQTT
  mosquitto:
    image: eclipse-mosquitto   # Ime slike
    container_name: mosquitto  # Ime kontejnerja
    restart: unless-stopped    # Samodejni ponovni zagon kontejnerja ob zaustavitvi (razen, ko to 탑elimo)
    ports:
      - "1883:1883"            # MQTT privzeti port
    volumes:                   # Priklop konfiguracijske datoteke v kontejner
      - ./data_mosquitto:/etc/mosquitto                                   
      - ./data_mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf  # Potrebno ustvariti datoteko mosquitto.conf
    networks:
      - mqtt-net               # Nastavimo omre탑je

networks:           
  mqtt-net:                    # Ustvarimo omre탑je z imenom mqtt-net
    name: mqtt-net

    # Vsebina datoteke mosquitto.conf
    # allow_anonymous true                   # Omogo훾imo anonimni dostop
    # listener 1883                          # Nastavimo port

    # OPCIJSKO
    # persistence true                       # Nastavimo, da se podatki vrst shranjujejo na disk (namesto v pomnilnik)
    # persistance_location /mosquitto/data/  # Pot za shranjevanje vrst na disk