global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "mqtt"
    static_configs:
      - targets: ['exporter:9234']
  - job_name: 'python-app'
    static_configs:
      - targets: ['host.docker.internal:8000']